spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:mysql://localhost:3306/user_db
#    username: root
#    password: root
    username: "{cipher}3f002393c6a04e00c0ee1381016187863921235ff0ea4cff0fbc134390ea8428"
    password: "{cipher}3f002393c6a04e00c0ee1381016187863921235ff0ea4cff0fbc134390ea8428"
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false
#  main:
#    allow-circular-references: true

server:
   port: 8080 # This is the default port anyway, but you can change it here
   servlet:
     context-path: /api

security:
  jwt:
    token:
      secret-key: '{cipher}8945c1bb5c0e26aa8373633fe022d0b4a2944a75ff7b5ac204a82ad2c171ace8'
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
